// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj337EPl5h5rvEkX3uNOiT5flkUNATiQU',
    appId: '1:982103673490:web:9b3b9e41028775c425f44b',
    messagingSenderId: '982103673490',
    projectId: 'cinn-f10bb',
    authDomain: 'cinn-f10bb.firebaseapp.com',
    storageBucket: 'cinn-f10bb.firebasestorage.app',
    measurementId: 'G-YBT2RCCFV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAMf7ruH4GA8rDpCDSNlj-M1ENlFmj4Bw',
    appId: '1:982103673490:android:3fa378adc1ddc8f525f44b',
    messagingSenderId: '982103673490',
    projectId: 'cinn-f10bb',
    storageBucket: 'cinn-f10bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ6IJ8A4GfRwWGoIiriw5-qq5y_ivy7gw',
    appId: '1:982103673490:ios:06ad146a9afca82c25f44b',
    messagingSenderId: '982103673490',
    projectId: 'cinn-f10bb',
    storageBucket: 'cinn-f10bb.firebasestorage.app',
    androidClientId: '982103673490-6utkd9cvgmsfg0ss8nonq4vrd314cdk8.apps.googleusercontent.com',
    iosClientId: '982103673490-25q56dnq3boao8434if94l2u5phad3a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.vff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ6IJ8A4GfRwWGoIiriw5-qq5y_ivy7gw',
    appId: '1:982103673490:ios:06ad146a9afca82c25f44b',
    messagingSenderId: '982103673490',
    projectId: 'cinn-f10bb',
    storageBucket: 'cinn-f10bb.firebasestorage.app',
    androidClientId: '982103673490-6utkd9cvgmsfg0ss8nonq4vrd314cdk8.apps.googleusercontent.com',
    iosClientId: '982103673490-25q56dnq3boao8434if94l2u5phad3a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.vff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj337EPl5h5rvEkX3uNOiT5flkUNATiQU',
    appId: '1:982103673490:web:d6aff7a66e8d40e925f44b',
    messagingSenderId: '982103673490',
    projectId: 'cinn-f10bb',
    authDomain: 'cinn-f10bb.firebaseapp.com',
    storageBucket: 'cinn-f10bb.firebasestorage.app',
    measurementId: 'G-WMWHQ030VS',
  );
}
